[package]
name = "poly_algebra"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits.workspace = true
num-bigint.workspace = true
rand_core.workspace = true

[dev-dependencies]
rand_chacha.workspace = true
