[package]
name = "dstu4145-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
signature.workspace = true
poly_algebra.workspace = true
rust-ec.workspace = true
num-traits.workspace = true
num-bigint.workspace = true
thiserror.workspace = true
rand_chacha.workspace = true
sha3.workspace = true